name: CI (Self-hosted) — Build & Push to Harbor

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  PROJECT: library
  IMAGE_NAME: test-server
  TAG: ${{ github.sha }}
  REGISTRY: harbor.internal:${{ secrets.KONG_PORT }}   # GỘP host+port vào 1 biến

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Debug kết nối
      - name: Debug connectivity
        run: |
          echo "REGISTRY=${{ env.REGISTRY }}"
          echo "== /etc/hosts =="
          grep -E 'harbor\.internal' /etc/hosts || true
          echo "== /v2/ =="
          curl -sv -H "Host: harbor.internal" http://${{ env.REGISTRY }}/v2/ | head -n 20 || true

      # Xoá auth cũ có thể gây nhầm host/port
      - name: Cleanup old docker auth
        run: |
          docker logout harbor.internal || true
          docker logout harbor.internal:80 || true
          docker logout ${{ env.REGISTRY }} || true

      # Login đúng host:port
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}           # << dùng host:port
          username: ${{ secrets.HARBOR_USERNAME }} # ví dụ: robot$library+ci
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Show Docker auth (masked)
        run: |
          cat ~/.docker/config.json | sed 's/"auth": *"[^"]*"/"auth":"***"/g' || true

      # Build & push, TAGS phải gồm host:port
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:latest
