name: CI — Build and Push to Harbor

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  # Đã cập nhật: Đây là endpoint công khai, có thể truy cập từ internet
  REGISTRY: harbor.snapnbuy.net
  PROJECT: library
  IMAGE_NAME: test-server
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    # Chạy trên self-hosted runner của bạn
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # --- BƯỚC DEBUG ĐÃ SỬA LẠI ---
      # Kiểm tra kết nối đến endpoint công khai, không còn dùng harbor.internal
      - name: Debug Harbor connectivity
        run: |
          echo "--- Checking DNS for ${{ env.REGISTRY }} ---"
          dig ${{ env.REGISTRY }} || nslookup ${{ env.REGISTRY }}

          echo "--- Checking connection to ${{ env.REGISTRY }} via HTTPS ---"
          # Kết nối qua HTTPS (port 443) vì đã có SSL
          curl -v https://${{ env.REGISTRY }}/v2/

      # --- BƯỚC LOGIN ĐÃ CẢI TIẾN BẢO MẬT ---
      # Sử dụng GitHub Secrets thay vì hardcode user/pass
      - name: Docker login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.REGISTRY }} \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      # Build image
      - name: Build image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .

      # Push image
      - name: Push image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          docker push "$IMAGE"

      # (Tùy chọn) Tag và push "latest" nếu là nhánh main
      - name: Tag & push latest
        if: github.ref == 'refs/heads/main'
        run: |
          BASE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}"
          docker tag "$BASE:${{ env.TAG }}" "$BASE:latest"
          docker push "$BASE:latest"
