name: CI (Self-hosted) — Build & Push to Harbor

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  REGISTRY_HOST: harbor.internal
  PROJECT: library           # <- đúng project của robot
  IMAGE_NAME: test-server
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Debug kết nối & DNS/Host/Port ngay trên runner context
      - name: Debug connectivity to Harbor via Kong
        run: |
          echo "KONG_PORT=${{ secrets.KONG_PORT }}"
          echo "== /etc/hosts =="
          grep -E 'harbor\.internal' /etc/hosts || true
          echo "== check /v2/ =="
          curl -sv -H "Host: harbor.internal" \
            http://harbor.internal:${{ secrets.KONG_PORT }}/v2/ | head -n 20 || true
          echo "== check /service/token =="
          curl -sv -H "Host: harbor.internal" \
            "http://harbor.internal:${{ secrets.KONG_PORT }}/service/token?service=harbor-registry&scope=repository:${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:push" \
            | head -n 20 || true

      # Đăng nhập bằng action official (nhớ secrets đúng)
      - name: Login to Harbor (robot of 'library')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}:${{ secrets.KONG_PORT }}
          username: ${{ secrets.HARBOR_USERNAME }}   # ví dụ: robot$library+ci
          password: ${{ secrets.HARBOR_PASSWORD }}

      # In ra config để chắc chắn đã có auth (ẩn password)
      - name: Show Docker auth config (masked)
        run: |
          cat ~/.docker/config.json | sed 's/"auth": *"[^"]*"/"auth":"***"/g' || true

      # Build & Push
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}:${{ secrets.KONG_PORT }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY_HOST }}:${{ secrets.KONG_PORT }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:latest
