name: CI — Hardcoded Harbor Test

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  PROJECT: library
  IMAGE_NAME: test-server
  TAG: ${{ github.sha }}
  REGISTRY: harbor.internal:52394   # đổi port này thành đúng NodePort Kong expose

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Debug endpoint Harbor
      - name: Debug Harbor connectivity
        run: |
          echo "Check harbor.internal DNS & curl"
          getent hosts harbor.internal || true
          curl -v -H "Host: harbor.internal" http://${{ env.REGISTRY }}/v2/ || true

      # Docker login với hardcode user/pass
      - name: Docker login Harbor (hardcoded robot account)
        run: |
          echo -n 'wJoKqc7XdEs9dz0jdHb9BaRyoiqgwBob' | \
            docker login ${{ env.REGISTRY }} \
              -u 'robot$library+ci' --password-stdin

      # Build image
      - name: Build image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .

      # Push image
      - name: Push image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          docker push "$IMAGE"

      # (Optional) Tag latest
      - name: Tag & push latest
        if: github.ref == 'refs/heads/main'
        run: |
          BASE="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}"
          docker tag "$BASE:${{ env.TAG }}" "$BASE:latest"
          docker push "$BASE:latest"
